version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers

    steps:
      - checkout
      
      - run:
          name: build dependencies
          command: bundle install
      
      - run:
          name: build the jekyll site
          command: build exec jekyll build

      - run:
          name: print the current time
          command: date
